name: solvent
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - conda-forge::python=3.8
  - conda-forge::setuptools=59.5.0
  - conda-forge::pip
  - conda-forge::openmm=7.5.1
  - conda-forge::pdbfixer
  - conda-forge::cudatoolkit==11.3.*
  - pytorch::pytorch=1.12.*
  - pip:
      - biopython==1.81
      - biotite==0.36.1
      - dm-tree==0.1.8
      - ml-collections==0.1.1
      - numpy==1.21.5
      - PyYAML==6.0
      - einops==0.6.0
      - transformers==4.26.1
      - fair-esm==2.0.0
      - igfold==0.3.1
      - ray==2.3.0
      - torchvision==0.13.1
      - pandas==1.3.5
      - scipy==1.7.3
      - git+https://github.com/facebookresearch/detectron2.git@86fc8c6fd6d46b40efbe5f449649722b43feeda6