MODEL:
  META_ARCHITECTURE: 'SSPF'
  NUM_RECYCLE: 3
  EMBEDDER:
    NAME: 'ESM'
    WEIGHT_KEY: 'pretrained_model/esm2_t12_35M_UR50D.pt'
    FREEZE: False
    NUM_LAYERS: 12
    NUM_HEADS: 20
    HIDDEN_DIM: 480
  TRUNK:
    NAME: 'Evoformer'
    NUM_BLOCKS: 1
  FOLDING:
    NAME: 'AlphafoldStructure'
  HEAD:
    TM:
      ENABLED: True
    VIOLATION:
      LOSS_WEIGHT: 0.0
SOLVER:
  STEPS: (80000,)
  MAX_ITER: 125000
  BASE_LR: 0.001
  GAMMA: 0.95
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: norm
    CLIP_VALUE: 0.1
  CHECKPOINT_PERIOD: 20000
DATASETS:
  TRAIN: ("pdb", "af2_uniref50",)
  TEST: ("cameo",)
INPUT:
  CROP:
    SIZE: 256
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  SAMPLER_TRAIN: 'WeightedTrainingSampler'